/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menu_perpustakaan;

import Connection.koneksi;
import Login_perpustakaan.input_regist;
import java.sql.Connection;
import javax.swing.JOptionPane;

/**
 *
 * @author llawl
 */
public class form_tentang extends javax.swing.JFrame {
    private Connection conn = new koneksi().connect();
    public static String nama;
    /**
     * Creates new form form_tentang
     */
    public form_tentang() {
        initComponents();
        txtnmlngkp.setText(input_regist.getnama());
        String KD = UserID.getUserLogin();
        txtnmlngkp.setText(KD);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        bexit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        bdaftar_buku = new javax.swing.JButton();
        btambah_buku = new javax.swing.JButton();
        btambah_anggota = new javax.swing.JButton();
        txtnmlngkp = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btentang = new javax.swing.JButton();
        bpengembalian_buku = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(245, 245, 245));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 204, 102));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(245, 245, 245));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 240, -1));

        bexit.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        bexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/exit_50px.png"))); // NOI18N
        bexit.setText(" Keluar");
        bexit.setBorder(null);
        bexit.setContentAreaFilled(false);
        bexit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bexit.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bexitActionPerformed(evt);
            }
        });
        jPanel3.add(bexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 240, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/administrator_male_30px.png"))); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        bdaftar_buku.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        bdaftar_buku.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/books_50px.png"))); // NOI18N
        bdaftar_buku.setText(" Daftar Buku");
        bdaftar_buku.setBorder(null);
        bdaftar_buku.setBorderPainted(false);
        bdaftar_buku.setContentAreaFilled(false);
        bdaftar_buku.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bdaftar_buku.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bdaftar_buku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdaftar_bukuActionPerformed(evt);
            }
        });
        jPanel3.add(bdaftar_buku, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 240, 50));

        btambah_buku.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        btambah_buku.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/add_book_50px.png"))); // NOI18N
        btambah_buku.setText(" Tambah Buku");
        btambah_buku.setBorder(null);
        btambah_buku.setContentAreaFilled(false);
        btambah_buku.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btambah_buku.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btambah_buku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btambah_bukuActionPerformed(evt);
            }
        });
        jPanel3.add(btambah_buku, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 240, 50));

        btambah_anggota.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        btambah_anggota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/add_user_male_50px.png"))); // NOI18N
        btambah_anggota.setText(" Tambah Anggota");
        btambah_anggota.setBorder(null);
        btambah_anggota.setContentAreaFilled(false);
        btambah_anggota.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btambah_anggota.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btambah_anggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btambah_anggotaActionPerformed(evt);
            }
        });
        jPanel3.add(btambah_anggota, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 240, 50));

        txtnmlngkp.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        txtnmlngkp.setText("Nama Lengkap Admin");
        jPanel3.add(txtnmlngkp, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/about_50px.png"))); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, -1, -1));

        jButton10.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/borrow_book_50px.png"))); // NOI18N
        jButton10.setText(" Peminjaman Buku");
        jButton10.setBorder(null);
        jButton10.setContentAreaFilled(false);
        jButton10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 240, 50));

        jPanel5.setBackground(new java.awt.Color(245, 245, 245));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btentang.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        btentang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/about_50px.png"))); // NOI18N
        btentang.setText(" Tentang");
        btentang.setBorder(null);
        btentang.setContentAreaFilled(false);
        btentang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btentang.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btentang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btentangActionPerformed(evt);
            }
        });
        jPanel5.add(btentang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 240, 50));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 240, 70));

        bpengembalian_buku.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        bpengembalian_buku.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/return_book_50px.png"))); // NOI18N
        bpengembalian_buku.setText(" Pengembalian Buku");
        bpengembalian_buku.setBorder(null);
        bpengembalian_buku.setContentAreaFilled(false);
        bpengembalian_buku.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bpengembalian_buku.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bpengembalian_buku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpengembalian_bukuActionPerformed(evt);
            }
        });
        jPanel3.add(bpengembalian_buku, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 240, 50));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 610));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel3.setText("<html>\nUNIVERSITAS INDRAPRASTA PGRI\n<br>\nFAKULTAS TEKNIK ILMU KOMPUTER\n<br>\nPROGRAM STUDI TEKNIK INFORMATIKA\n</html>");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Logo Unindra Universitas Indraprasta PGRI1.png"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 560, 10));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Aplikasi ini dibuat untuk memenuhi syarat kelulusan Strata 1 (S1)");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Perancang Aplikasi dan Laporan KKP adalah sebagai berikut :");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("1. Mohamad Noor Alam (201743502073)");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("2. Aris Muhammad Haris (201743500942)");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setText("3. Muhammad Zamil Fadillah (201743502508)");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setText("4. Zepry Setiawan (201743501322)");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setText("5. Darmawan Bayu AJi (201843579017)");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setText("6. Syifa Luthfiah (201743502466)");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel15.setText("7. Hani Libnawati (201743502174)");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 420, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Hubungi Kami : 085924581491");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 530, 260, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 1, 800, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btentangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btentangActionPerformed
        dispose();
    }//GEN-LAST:event_btentangActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        dispose();
        input_peminjaman inpin;
        inpin = new input_peminjaman();
        inpin.setVisible(true);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void bexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bexitActionPerformed
        int tny = JOptionPane.showConfirmDialog(null, "Yakin Ingin Keluar ?","Tanya",JOptionPane.YES_NO_OPTION);
        if (tny==0) {
            try {
                dispose();
                dispose();
            } catch (Exception e) {
            }
        }
        new Login_perpustakaan.login().setVisible(true);
    }//GEN-LAST:event_bexitActionPerformed

    private void bdaftar_bukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdaftar_bukuActionPerformed
        dispose();
        daftar_buku dabuk;
        dabuk = new daftar_buku();
        dabuk.setVisible(true);
    }//GEN-LAST:event_bdaftar_bukuActionPerformed

    private void btambah_bukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btambah_bukuActionPerformed
        dispose();
        input_buku inbuk;
        inbuk = new input_buku();
        inbuk.setVisible(true);
    }//GEN-LAST:event_btambah_bukuActionPerformed

    private void btambah_anggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btambah_anggotaActionPerformed
        dispose();
        input_anggota insis;
        insis = new input_anggota();
        insis.setVisible(true);
    }//GEN-LAST:event_btambah_anggotaActionPerformed

    private void bpengembalian_bukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bpengembalian_bukuActionPerformed
        dispose();
        input_pengembalian inpeng;
        inpeng = new input_pengembalian();
        inpeng.setVisible(true);
    }//GEN-LAST:event_bpengembalian_bukuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_tentang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_tentang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_tentang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_tentang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form_tentang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bdaftar_buku;
    private javax.swing.JButton bexit;
    private javax.swing.JButton bpengembalian_buku;
    private javax.swing.JButton btambah_anggota;
    private javax.swing.JButton btambah_buku;
    private javax.swing.JButton btentang;
    private javax.swing.JButton jButton10;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel txtnmlngkp;
    // End of variables declaration//GEN-END:variables
}
