/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menu_perpustakaan;

import java.sql.*;
import Connection.koneksi;
import Login_perpustakaan.input_regist;
import javax.swing.JLabel;
import javax.swing.JOptionPane;


public class main_menu extends javax.swing.JFrame {
    private Connection conn = new koneksi().connect();
    public static String nama;
    
    
    
            
    /**
     * Creates new form main_menu
     */
    public main_menu() {
        initComponents();
        txtnmlngkp.setText(input_regist.getnama());
        String KD = UserID.getUserLogin();
        txtnmlngkp.setText(KD);
    }
   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btentang = new javax.swing.JButton();
        bdaftar_buku = new javax.swing.JButton();
        btambah_buku = new javax.swing.JButton();
        btambah_anggota = new javax.swing.JButton();
        bpinjam_buku = new javax.swing.JButton();
        bexit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtnmlngkp = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        bpengembalian_buku = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(245, 245, 245));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 204, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(245, 245, 245));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 530, 260, -1));

        btentang.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        btentang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/about_50px.png"))); // NOI18N
        btentang.setText("  Tentang");
        btentang.setBorder(null);
        btentang.setContentAreaFilled(false);
        btentang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btentang.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btentang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btentangActionPerformed(evt);
            }
        });
        jPanel2.add(btentang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, 240, 50));

        bdaftar_buku.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        bdaftar_buku.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/books_50px.png"))); // NOI18N
        bdaftar_buku.setText(" Daftar Buku");
        bdaftar_buku.setBorder(null);
        bdaftar_buku.setBorderPainted(false);
        bdaftar_buku.setContentAreaFilled(false);
        bdaftar_buku.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bdaftar_buku.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bdaftar_buku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdaftar_bukuActionPerformed(evt);
            }
        });
        jPanel2.add(bdaftar_buku, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 240, 50));

        btambah_buku.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        btambah_buku.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/add_book_50px.png"))); // NOI18N
        btambah_buku.setText(" Tambah Buku");
        btambah_buku.setBorder(null);
        btambah_buku.setContentAreaFilled(false);
        btambah_buku.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btambah_buku.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btambah_buku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btambah_bukuActionPerformed(evt);
            }
        });
        jPanel2.add(btambah_buku, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 240, 50));

        btambah_anggota.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        btambah_anggota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/add_user_male_50px.png"))); // NOI18N
        btambah_anggota.setText(" Tambah Anggota");
        btambah_anggota.setBorder(null);
        btambah_anggota.setContentAreaFilled(false);
        btambah_anggota.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btambah_anggota.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btambah_anggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btambah_anggotaActionPerformed(evt);
            }
        });
        jPanel2.add(btambah_anggota, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 240, 50));

        bpinjam_buku.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        bpinjam_buku.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/borrow_book_50px.png"))); // NOI18N
        bpinjam_buku.setText(" Peminjaman Buku");
        bpinjam_buku.setBorder(null);
        bpinjam_buku.setContentAreaFilled(false);
        bpinjam_buku.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bpinjam_buku.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bpinjam_buku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpinjam_bukuActionPerformed(evt);
            }
        });
        jPanel2.add(bpinjam_buku, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 240, 50));

        bexit.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        bexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/exit_50px.png"))); // NOI18N
        bexit.setText(" Keluar");
        bexit.setBorder(null);
        bexit.setContentAreaFilled(false);
        bexit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bexit.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bexitActionPerformed(evt);
            }
        });
        jPanel2.add(bexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 240, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/home_50px.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 50, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/administrator_male_30px.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        txtnmlngkp.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        txtnmlngkp.setText("Nama Lengkap Admin");
        jPanel2.add(txtnmlngkp, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 50, 0));

        bpengembalian_buku.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        bpengembalian_buku.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/return_book_50px.png"))); // NOI18N
        bpengembalian_buku.setText(" Pengembalian Buku");
        bpengembalian_buku.setBorder(null);
        bpengembalian_buku.setContentAreaFilled(false);
        bpengembalian_buku.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bpengembalian_buku.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bpengembalian_buku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpengembalian_bukuActionPerformed(evt);
            }
        });
        jPanel2.add(bpengembalian_buku, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 240, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 610));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/MENU.png"))); // NOI18N
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 660, 380));

        jPanel4.setBackground(new java.awt.Color(255, 255, 0));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("VISI");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("<html>\n\"UNGGUL DALAM PRESTASI, LUHUR DALAM BUDI PEKERTI <center>\nDAN BERPIJAK PADA IMAN DAN TAQWA\" <center>\n</html>");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 0, 420, 120));

        jPanel5.setBackground(new java.awt.Color(0, 204, 204));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("<html> <li> Meningkatkan keimanan dan ketaqwaan kepada Tuhan Yang Maha Esa. </li> <li>Melaksanakan proses pembelajaran dan bimbingan secara efektif dan terpadu. </li> <li>Menggali potensi siswa untuk dikembangkan secara optimal.</li> <li>Meningkatkan prestasi akademik dan non akademik.</li> <li>Menanamkan jiwa kemandirian dan rasa tanggung jawab.</li> <li>Menanamkan kedisiplinan dan ketertiban seluruh warga sekolah.</li> <li>Menanamkan budaya santun kepada seluruh warga sekolah.</li> <li>Mendorong siswa da guru terampil dalam teknologi informasi dan komunikasi.</li>  </html>");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 20, 420, 350));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("MISI");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, -1));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 130, 420, 400));

        jPanel6.setBackground(new java.awt.Color(0, 204, 102));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("<html> Jl. Raya Condet No.4 RT,5/RW3, Bale Kambang,kramat Jati, Jakarta Timur, 13530 <br> Email : adiluhur_stm2@yahoo.com http://smkadiluhur2.net Telp/Fax : [021] 8400 105 <br> </html> ");
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 570, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("<html> SISTEM INFORMASI PERPUSTAKAAN <br> SMK ADI LUHUR 2 JAKARTA </html>");
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 430, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menu_perpustakaan/minilogotransaparant1.png"))); // NOI18N
        jPanel6.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 120));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 680, 10));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 680, 530));

        jPanel7.setBackground(new java.awt.Color(0, 204, 102));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(245, 245, 245));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        jPanel7.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 0, 10, 90));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 540, 1110, 70));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 610));

        setSize(new java.awt.Dimension(1376, 646));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btentangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btentangActionPerformed
        //dispose();
        form_tentang fote;
        fote = new form_tentang();
        fote.setVisible(true);
    }//GEN-LAST:event_btentangActionPerformed

    private void bdaftar_bukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdaftar_bukuActionPerformed
        //dispose();
        daftar_buku dabuk;
        dabuk = new daftar_buku();
        dabuk.setVisible(true);
    }//GEN-LAST:event_bdaftar_bukuActionPerformed

    private void btambah_bukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btambah_bukuActionPerformed
        //dispose();
        input_buku inbuk;
        inbuk = new input_buku();
        inbuk.setVisible(true);
    }//GEN-LAST:event_btambah_bukuActionPerformed

    private void btambah_anggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btambah_anggotaActionPerformed
        //dispose();
        input_anggota insis;
        insis = new input_anggota();
        insis.setVisible(true);
    }//GEN-LAST:event_btambah_anggotaActionPerformed

    private void bpinjam_bukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bpinjam_bukuActionPerformed
        //dispose();
        input_peminjaman inpin;
        inpin = new input_peminjaman();
        inpin.setVisible(true);
    }//GEN-LAST:event_bpinjam_bukuActionPerformed

    private void bexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bexitActionPerformed
        int tny = JOptionPane.showConfirmDialog(null, "Yakin Ingin Keluar ?","Tanya",JOptionPane.YES_NO_OPTION);
        if (tny==0) {     
            try {
                dispose();
                dispose();
            } catch (Exception e) {
            }
        }
        new Login_perpustakaan.login().setVisible(true);
    }//GEN-LAST:event_bexitActionPerformed

    private void bpengembalian_bukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bpengembalian_bukuActionPerformed
        dispose();
        input_pengembalian inpeng;
        inpeng = new input_pengembalian();
        inpeng.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_bpengembalian_bukuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main_menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bdaftar_buku;
    private javax.swing.JButton bexit;
    private javax.swing.JButton bpengembalian_buku;
    private javax.swing.JButton bpinjam_buku;
    private javax.swing.JButton btambah_anggota;
    private javax.swing.JButton btambah_buku;
    private javax.swing.JButton btentang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel txtnmlngkp;
    // End of variables declaration//GEN-END:variables
}
