/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login_perpustakaan;

import java.sql.*;
import javax.swing.table.DefaultTableModel;
import Connection.koneksi;
import javax.swing.JOptionPane;


public class input_regist extends javax.swing.JFrame {
    private Connection conn = new koneksi().connect();
    private DefaultTableModel UserTab;
    public static String nama;
    String usrnm;

    public input_regist() {
        initComponents();
        UserModelTable();
        clear();
    }
    
    public static String getnama(){
        return nama;
    }
    
    public void clear(){
        txtnm.setText("");
        cbjenkel.setSelectedItem(null);
        txtemail.setText("");
        txtnotelp.setText("");
        txtusername.setText("");
        txtpass.setText("");
        
    }
    public void UserModelTable(){
        
        String nama = txtnm.getText();
        //String cari = txtcari.getText();
        Object [] Row ={"Username", "Password"};
        UserTab = new DefaultTableModel(null, Row);
        try{
            String sql = "SELECT * FROM tb_admin";
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                UserTab.addRow(new Object[]{
                    
                    rs.getString(1), 
                    rs.getString(2), 
                    rs.getString(3)});     
                }
                //tbuser.setModel(UserTab);
            }
        catch(SQLException ex){
            JOptionPane.showMessageDialog(this, "data gagal dipanggil "+ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        bexit = new javax.swing.JButton();
        bregis_menu = new javax.swing.JButton();
        bkelola = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        blogin_menu = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txtnm = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtnotelp = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtusername = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        bsave = new javax.swing.JButton();
        bubah = new javax.swing.JButton();
        cbjenkel = new javax.swing.JComboBox<>();
        txtpass = new javax.swing.JPasswordField();
        bcancel1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(245, 245, 245));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 204, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bexit.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        bexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/exit_50px.png"))); // NOI18N
        bexit.setText("  Keluar");
        bexit.setBorder(null);
        bexit.setBorderPainted(false);
        bexit.setContentAreaFilled(false);
        bexit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bexit.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bexitActionPerformed(evt);
            }
        });
        jPanel2.add(bexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 240, 50));

        bregis_menu.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        bregis_menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/add_user_group_woman_man_50px.png"))); // NOI18N
        bregis_menu.setText("  Registrasi");
        bregis_menu.setBorder(null);
        bregis_menu.setBorderPainted(false);
        bregis_menu.setContentAreaFilled(false);
        bregis_menu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bregis_menu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bregis_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bregis_menuActionPerformed(evt);
            }
        });
        jPanel2.add(bregis_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 240, 50));

        bkelola.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        bkelola.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/maintenance_50px.png"))); // NOI18N
        bkelola.setText("  Kelola Admin");
        bkelola.setBorder(null);
        bkelola.setBorderPainted(false);
        bkelola.setContentAreaFilled(false);
        bkelola.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bkelola.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bkelola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkelolaActionPerformed(evt);
            }
        });
        jPanel2.add(bkelola, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 240, 50));

        jPanel4.setBackground(new java.awt.Color(245, 245, 245));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 240, 70));

        blogin_menu.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        blogin_menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/enter_50px.png"))); // NOI18N
        blogin_menu.setText("  Masuk");
        blogin_menu.setBorder(null);
        blogin_menu.setBorderPainted(false);
        blogin_menu.setContentAreaFilled(false);
        blogin_menu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        blogin_menu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        blogin_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blogin_menuActionPerformed(evt);
            }
        });
        jPanel2.add(blogin_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 240, 50));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login_perpustakaan/minilogotransaparant2.png"))); // NOI18N
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 400));

        txtnm.setBackground(new java.awt.Color(245, 245, 245));
        txtnm.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtnm.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtnm, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, 370, 20));

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel1.setText("Nama Lengkap");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel2.setText("Jenis Kelamin");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, -1, -1));

        txtemail.setBackground(new java.awt.Color(245, 245, 245));
        txtemail.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtemail.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 370, 20));

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel3.setText("E - Mail");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel4.setText("No. Telepon");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, -1, -1));

        txtnotelp.setBackground(new java.awt.Color(245, 245, 245));
        txtnotelp.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtnotelp.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtnotelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 370, 20));

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel5.setText("Username");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, -1, -1));

        txtusername.setBackground(new java.awt.Color(245, 245, 245));
        txtusername.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtusername.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        txtusername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtusernameKeyPressed(evt);
            }
        });
        jPanel1.add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, 370, 20));

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel6.setText("Password");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/password_30px.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 30, 40));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/name_30px.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 30, 40));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/gender_30px.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 30, 40));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/mail_account_30px.png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 30, 40));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/phone_30px.png"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 30, 40));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/administrator_male_30px.png"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 30, 40));

        bsave.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        bsave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/save_20px.png"))); // NOI18N
        bsave.setText("Simpan");
        bsave.setBorder(null);
        bsave.setBorderPainted(false);
        bsave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsaveActionPerformed(evt);
            }
        });
        jPanel1.add(bsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, 80, 30));

        bubah.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        bubah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/edit_20px.png"))); // NOI18N
        bubah.setText("Ubah");
        bubah.setBorder(null);
        bubah.setBorderPainted(false);
        bubah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bubahActionPerformed(evt);
            }
        });
        jPanel1.add(bubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 340, 80, 30));

        cbjenkel.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        cbjenkel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih ...", "Laki - laki", "Perempuan" }));
        jPanel1.add(cbjenkel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 370, -1));

        txtpass.setBackground(new java.awt.Color(245, 245, 245));
        txtpass.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, 370, -1));

        bcancel1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        bcancel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/clear_symbol_20px.png"))); // NOI18N
        bcancel1.setText("Kosong");
        bcancel1.setBorder(null);
        bcancel1.setBorderPainted(false);
        bcancel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bcancel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcancel1ActionPerformed(evt);
            }
        });
        jPanel1.add(bcancel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 340, 80, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(726, 439));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bexitActionPerformed
        int tny = JOptionPane.showConfirmDialog(null, "Yakin Ingin Keluar ?","Tanya",JOptionPane.YES_NO_OPTION);
        if (tny==0) {     
            try {
                System.exit(0);
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_bexitActionPerformed

    private void blogin_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blogin_menuActionPerformed
        dispose();
        login masuk;
        masuk = new login();
        masuk.setVisible(true);
    }//GEN-LAST:event_blogin_menuActionPerformed

    private void bregis_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bregis_menuActionPerformed
        //input_regist regis;
        //regis = new input_regist();
        //regis.setVisible(true);

    }//GEN-LAST:event_bregis_menuActionPerformed

    private void bkelolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkelolaActionPerformed
        dispose();
        form_kelolaUser kelola;
        kelola = new form_kelolaUser();
        kelola.setVisible(true);
    }//GEN-LAST:event_bkelolaActionPerformed

    private void bsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsaveActionPerformed
        String sql = "insert into tb_admin values (?,?,?,?,?,?)";
        try{
            PreparedStatement st = conn.prepareStatement(sql);
            
            st.setString(1, txtusername.getText());
            st.setString(2, String.valueOf(txtpass.getPassword()));
            st.setString(3, txtnm.getText());
            st.setString(4, cbjenkel.getItemAt(cbjenkel.getSelectedIndex()));
            st.setString(5, txtemail.getText());
            st.setString(6, txtnotelp.getText());
            
            st.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data Berhasil Disimpan");
            clear();
            txtusername.requestFocus();
            
            
            }catch(SQLException ex){
            JOptionPane.showMessageDialog(this, "Data gagal Disimpan " +ex);
            }
        //UserModelTable();

    }//GEN-LAST:event_bsaveActionPerformed

    private void bubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bubahActionPerformed
        try {
            String sql = "update tb_admin set nama_admin=?,jenkel=?,email=?,no_telp=?, password=? where id_admin= '"+txtusername.getText()+"'";
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, txtnm.getText());
            stat.setString(2, cbjenkel.getItemAt(cbjenkel.getSelectedIndex()));
            stat.setString(3, txtemail.getText());
            stat.setString(4, txtnotelp.getText());
            stat.setString(5, txtpass.getText());
            
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "data berhasil Diubah");
            clear();
            txtusername.requestFocus();
        }
        catch (SQLException e){
            JOptionPane.showMessageDialog(null, "Data Gagal Diubah" +e);
        }
        UserModelTable();
    }//GEN-LAST:event_bubahActionPerformed

    private void txtusernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtusernameKeyPressed
        usrnm=txtusername.getText();
        int ascii = evt.getKeyCode();
        if(ascii==10){
            try {
                String sql="select * from tb_admin where id_admin='"+ usrnm +"'";
                Statement st=conn.createStatement();
                ResultSet rsusrnm = st.executeQuery(sql);
                while (rsusrnm.next()){
                    txtnm.setText(rsusrnm.getString(3));
                    cbjenkel.setSelectedItem(rsusrnm.getString(4));
                    txtemail.setText(rsusrnm.getString(5));
                    txtnotelp.setText(rsusrnm.getString(6));
                    txtpass.setText(rsusrnm.getString(2));
                    //bdelete.enable(true);
                    //bedit.enable(true);

                }
            } catch (Exception e) {
                JOptionPane.showConfirmDialog(null, "Data Tidak Di Temukan ....!! \n"
                    +e.getMessage());
                txtusername.requestFocus();
            }
        }
    }//GEN-LAST:event_txtusernameKeyPressed

    private void bcancel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcancel1ActionPerformed
        clear();
    }//GEN-LAST:event_bcancel1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(input_regist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(input_regist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(input_regist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(input_regist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new input_regist().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bcancel1;
    private javax.swing.JButton bexit;
    private javax.swing.JButton bkelola;
    private javax.swing.JButton blogin_menu;
    private javax.swing.JButton bregis_menu;
    private javax.swing.JButton bsave;
    private javax.swing.JButton bubah;
    private javax.swing.JComboBox<String> cbjenkel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtnm;
    private javax.swing.JTextField txtnotelp;
    private javax.swing.JPasswordField txtpass;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
